#ifndef ENTROPY_STATS_H
#define ENTROPY_STATS_H

/*
 * Statistical tests over generated bytes and over a raw timing-sample
 * stream. Pure functions, no Windows dependency, so they can be unit
 * tested standalone (see tests/test_entropy_stats.c).
 *
 * These are diagnostic estimators for an engineering dashboard, not a
 * certified SP 800-90B / FIPS 140 validation suite. For the library's own,
 * authoritative RCT/APT/Lag pass-fail state (computed internally on the
 * raw noise source, which this module has no access to), see
 * rng_get_status_json() / jent_status() instead: entropy_stats_rct() and
 * entropy_stats_apt() in this file apply the textbook SP 800-90B formulas
 * to whatever sample stream the caller hands them -- for this dashboard,
 * the collector's own per-call timing-latency samples, a coarse proxy for
 * the real noise source, not the real noise source itself.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ENTROPY_STATS_BINS 256

typedef struct entropy_histogram {
	uint64_t counts[ENTROPY_STATS_BINS];
	uint64_t total;
} entropy_histogram;

void entropy_stats_histogram(const unsigned char *data, size_t len,
			     entropy_histogram *out);

/* Shannon entropy of the byte distribution, bits/byte, range [0, 8]. */
double entropy_stats_shannon(const entropy_histogram *h);

/*
 * Min-entropy of the byte distribution: -log2(max probability), bits/byte,
 * range [0, 8]. The figure that actually bounds an attacker's best guessing
 * strategy; Shannon entropy does not.
 */
double entropy_stats_min_entropy(const entropy_histogram *h);

typedef struct entropy_chi_square {
	double statistic; /* sum((observed-expected)^2/expected), df = 255 */
	/*
	 * P(X >= statistic) under chi-square(255 df), via the Wilson-Hilferty
	 * cube-root normal approximation (accurate to a few percent for
	 * df >= 30; exact for our fixed df = 255). Not the exact regularized
	 * incomplete gamma function -- adequate for a diagnostic reading, not
	 * exact enough to cite as a certified statistical result.
	 */
	double p_value;
} entropy_chi_square;

entropy_chi_square entropy_stats_chi_square(const entropy_histogram *h);

typedef struct entropy_monobit {
	int64_t bit_total;
	int64_t ones;
	double statistic; /* |S_n| / sqrt(n) */
	double p_value;   /* erfc(statistic / sqrt(2)); SP 800-22 2.1 */
} entropy_monobit;

entropy_monobit entropy_stats_monobit(const unsigned char *data, size_t len);

/*
 * Lag-1 serial correlation coefficient over bytes (the formula used by
 * John Walker's `ent` tool and by Knuth vol. 2): how much each byte value
 * predicts the next one, in [-1, 1]. 0 is uncorrelated. NAN if len < 2, or
 * if every byte has the same value (correlation is undefined, not zero).
 */
double entropy_stats_serial_correlation(const unsigned char *data,
					size_t len);

typedef struct entropy_runs {
	int64_t bit_total;
	int64_t ones;
	double proportion; /* ones / bit_total */
	/*
	 * SP 800-22 2.3's own pre-condition: false when |proportion - 0.5| is
	 * too large for the runs count to be a meaningful diagnostic at all.
	 * observed_runs and p_value are still filled in when !applicable, but
	 * should not be read as a pass/fail signal.
	 */
	bool applicable;
	int64_t observed_runs;
	double p_value;
} entropy_runs;

entropy_runs entropy_stats_runs(const unsigned char *data, size_t len);

/* Aggregate byte-level report bundling every test above. */
typedef struct entropy_report {
	size_t byte_count;
	double shannon_bits_per_byte;
	double min_entropy_bits_per_byte;
	entropy_chi_square chi_square;
	entropy_monobit monobit;
	double serial_correlation;
	entropy_runs runs;
	uint64_t histogram[ENTROPY_STATS_BINS];
} entropy_report;

void entropy_stats_report(const unsigned char *data, size_t len,
			  entropy_report *out);

typedef struct entropy_rct_result {
	unsigned int cutoff;  /* C = 1 + ceil(-log2(alpha) / h_bits) */
	unsigned int max_run; /* longest run of consecutive identical samples */
	bool passed;          /* max_run < cutoff */
} entropy_rct_result;

/*
 * SP 800-90B section 4.4.1 Repetition Count Test, generic form: fails when
 * the same value repeats too many times in a row to be plausible for a
 * source with h_bits of min-entropy per sample.
 *   alpha: intended false-positive rate, e.g. 2^-20.
 *   h_bits: assumed worst-case min-entropy per sample; 1.0 if unknown.
 */
entropy_rct_result entropy_stats_rct(const double *samples, size_t n,
				     double alpha, double h_bits);

typedef struct entropy_apt_result {
	unsigned int window_size;
	unsigned int cutoff;
	unsigned int windows_tested;
	unsigned int windows_failed;
	bool passed;
} entropy_apt_result;

/*
 * SP 800-90B section 4.4.2 Adaptive Proportion Test, generic form: in each
 * non-overlapping window, counts how often the window's first value
 * reoccurs, and fails a window when that count is implausibly high. The
 * per-window cutoff is a normal approximation to the exact binomial
 * quantile (continuity-corrected); expect it to be within a count or two
 * of a table computed by exact inversion.
 */
entropy_apt_result entropy_stats_apt(const double *samples, size_t n,
				     unsigned int window_size, double alpha,
				     double h_bits);

#ifdef __cplusplus
}
#endif

#endif
