#include "benchmark.h"
#include "entropy_stats.h"
#include "health_monitor.h"
#include "rng_wrapper.h"

#include <errno.h>
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define DEFAULT_RANDOM_BYTE_COUNT 32U
#define DEFAULT_BENCHMARK_BYTES 1024U
#define DEFAULT_BENCHMARK_ITERATIONS 1000
#define RANDOM_OUTPUT_FILE "random.bin"
#define STATUS_JSON_BUFFER_SIZE 4096U

static void print_usage(const char *program_name)
{
	fprintf(stderr,
		"Usage: %s [options]\n"
		"Options:\n"
		"  --bytes N             Generate N random bytes (default: 32)\n"
		"  --write               Write raw bytes to random.bin\n"
		"  --prompt-write        Ask whether to write raw bytes to random.bin\n"
		"  --benchmark [N I]     Benchmark N bytes per call for I iterations\n"
		"  --status              Print health status and library status (JSON) before exit\n"
		"  --stats               Print entropy analysis of the generated bytes\n"
		"  --osr N               Oversampling rate passed to the collector (default: library choice)\n"
		"  --force-fips          Enforce full SP800-90B compliance (JENT_FORCE_FIPS)\n"
		"  --ntg1                Enforce AIS 20/31 NTG.1 compliance (JENT_NTG1)\n"
		"  --no-memory-access    Disable memory access noise source (less entropy, less RAM)\n"
		"  --help                Show this help\n",
		program_name);
}

static void print_entropy_report(const unsigned char *data, size_t len)
{
	entropy_report r;

	entropy_stats_report(data, len, &r);

	printf("\nEntropy analysis (%zu bytes)\n", r.byte_count);
	printf("+--------------------------------+----------------------+\n");
	printf("| Shannon entropy                | %15.4f bits/B |\n", r.shannon_bits_per_byte);
	printf("| Min-entropy                    | %15.4f bits/B |\n", r.min_entropy_bits_per_byte);
	printf("| Chi-square statistic (df=255)  | %20.2f |\n", r.chi_square.statistic);
	printf("| Chi-square p-value             | %20.4f |\n", r.chi_square.p_value);
	printf("| Monobit p-value (SP800-22 2.1) | %20.4f |\n", r.monobit.p_value);
	if (r.runs.applicable)
		printf("| Runs p-value (SP800-22 2.3)    | %20.4f |\n", r.runs.p_value);
	else
		printf("| Runs test                      |    not applicable   |\n");
	if (isnan(r.serial_correlation))
		printf("| Serial correlation (lag-1)     |    undefined (n<2)  |\n");
	else
		printf("| Serial correlation (lag-1)     | %20.4f |\n", r.serial_correlation);
	printf("+--------------------------------+----------------------+\n");
	printf("A p-value below ~0.01 flags a deviation from randomness worth investigating;\n"
	       "it is not proof the source is compromised, and passing is not proof it is safe.\n");
}

static int parse_size(const char *text, size_t *value)
{
	unsigned long long parsed;
	char *endptr;

	if (!text || !value)
		return -1;

	errno = 0;
	parsed = strtoull(text, &endptr, 10);
	if (errno || endptr == text || *endptr != '\0')
		return -1;
	if (parsed > (unsigned long long)SIZE_MAX)
		return -1;

	*value = (size_t)parsed;
	return 0;
}

static int parse_int(const char *text, int *value)
{
	long parsed;
	char *endptr;

	if (!text || !value)
		return -1;

	errno = 0;
	parsed = strtol(text, &endptr, 10);
	if (errno || endptr == text || *endptr != '\0' || parsed <= 0 ||
	    parsed > 2147483647L)
		return -1;

	*value = (int)parsed;
	return 0;
}

static bool should_prompt_write(void)
{
	char answer[8];

	printf("Write raw bytes to %s? [y/N]: ", RANDOM_OUTPUT_FILE);
	if (!fgets(answer, sizeof(answer), stdin))
		return false;

	return answer[0] == 'y' || answer[0] == 'Y';
}

static int write_random_file(const unsigned char *buffer, size_t len)
{
	FILE *file;

	file = fopen(RANDOM_OUTPUT_FILE, "wb");
	if (!file)
		return -1;

	if (fwrite(buffer, 1, len, file) != len) {
		fclose(file);
		return -1;
	}

	if (fclose(file))
		return -1;

	return 0;
}

int main(int argc, char **argv)
{
	unsigned char *random_bytes = NULL;
	size_t random_byte_count = DEFAULT_RANDOM_BYTE_COUNT;
	size_t benchmark_bytes = DEFAULT_BENCHMARK_BYTES;
	int benchmark_iterations = DEFAULT_BENCHMARK_ITERATIONS;
	bool write_output = false;
	bool prompt_write = false;
	bool run_benchmark_mode = false;
	bool print_status = false;
	bool print_stats = false;
	rng_settings settings;
	int ret;
	int i;
	size_t j;

	rng_settings_defaults(&settings);

	for (i = 1; i < argc; i++) {
		if (strcmp(argv[i], "--bytes") == 0) {
			if (++i >= argc || parse_size(argv[i], &random_byte_count)) {
				print_usage(argv[0]);
				return 2;
			}
		} else if (strcmp(argv[i], "--write") == 0) {
			write_output = true;
		} else if (strcmp(argv[i], "--prompt-write") == 0) {
			prompt_write = true;
		} else if (strcmp(argv[i], "--benchmark") == 0) {
			run_benchmark_mode = true;
			if (i + 2 < argc && argv[i + 1][0] != '-' &&
			    argv[i + 2][0] != '-') {
				if (parse_size(argv[i + 1], &benchmark_bytes) ||
				    parse_int(argv[i + 2], &benchmark_iterations)) {
					print_usage(argv[0]);
					return 2;
				}
				i += 2;
			}
		} else if (strcmp(argv[i], "--status") == 0) {
			print_status = true;
		} else if (strcmp(argv[i], "--stats") == 0) {
			print_stats = true;
		} else if (strcmp(argv[i], "--osr") == 0) {
			size_t osr_val;
			if (++i >= argc || parse_size(argv[i], &osr_val) ||
			    osr_val > 65535) {
				print_usage(argv[0]);
				return 2;
			}
			settings.osr = (unsigned int)osr_val;
		} else if (strcmp(argv[i], "--force-fips") == 0) {
			settings.force_fips = true;
		} else if (strcmp(argv[i], "--ntg1") == 0) {
			settings.ntg1 = true;
		} else if (strcmp(argv[i], "--no-memory-access") == 0) {
			settings.disable_memory_access = true;
		} else if (strcmp(argv[i], "--help") == 0) {
			print_usage(argv[0]);
			return 0;
		} else {
			print_usage(argv[0]);
			return 2;
		}
	}

	ret = rng_configure(&settings);
	if (ret) {
		fprintf(stderr, "Failed to apply RNG settings: %d\n", ret);
		return 1;
	}

	if (run_benchmark_mode) {
		ret = run_benchmark(benchmark_bytes, benchmark_iterations, NULL);
		if (print_status) {
			char status_json[STATUS_JSON_BUFFER_SIZE];
			health_monitor_print_report(stdout);
			if (rng_get_status_json(status_json, sizeof(status_json)) == 0)
				printf("\nLibrary status:\n%s", status_json);
		}
		return ret ? 1 : 0;
	}

	if (!random_byte_count) {
		fprintf(stderr, "--bytes must be greater than zero\n");
		return 2;
	}

	random_bytes = malloc(random_byte_count);
	if (!random_bytes) {
		fprintf(stderr, "Failed to allocate %zu bytes\n", random_byte_count);
		return 1;
	}

	ret = init_rng();
	if (ret) {
		fprintf(stderr, "Failed to initialize RNG: %d\n", ret);
		free(random_bytes);
		return 1;
	}

	ret = get_random_bytes(random_bytes, random_byte_count);
	if (ret) {
		fprintf(stderr, "Failed to generate random bytes: %d\n", ret);
		shutdown_rng();
		rng_secure_zero(random_bytes, random_byte_count);
		free(random_bytes);
		return 1;
	}

	for (j = 0; j < random_byte_count; j++)
		printf("%02x", random_bytes[j]);
	printf("\n");

	if (prompt_write && !write_output)
		write_output = should_prompt_write();

	if (write_output && write_random_file(random_bytes, random_byte_count)) {
		fprintf(stderr, "Failed to write %s\n", RANDOM_OUTPUT_FILE);
		shutdown_rng();
		rng_secure_zero(random_bytes, random_byte_count);
		free(random_bytes);
		return 1;
	}

	if (print_stats)
		print_entropy_report(random_bytes, random_byte_count);

	if (print_status) {
		char status_json[STATUS_JSON_BUFFER_SIZE];

		health_monitor_print_report(stdout);
		if (rng_get_status_json(status_json, sizeof(status_json)) == 0)
			printf("\nLibrary status:\n%s", status_json);
	}

	shutdown_rng();
	rng_secure_zero(random_bytes, random_byte_count);
	free(random_bytes);
	return 0;
}
